GRANT ALL ON SCHEMA "internal" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
GRANT ALL ON FUNCTION "public"."addfreeadventure"("adventureid" bigint) TO "postgres";
GRANT ALL ON FUNCTION "public"."addfreeadventure"("adventureid" bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."addfreeadventure"("adventureid" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."addfreeadventure"("adventureid" bigint) TO "service_role";
GRANT ALL ON FUNCTION "public"."advancetonextpuzzle"() TO "postgres";
GRANT ALL ON FUNCTION "public"."advancetonextpuzzle"() TO "anon";
GRANT ALL ON FUNCTION "public"."advancetonextpuzzle"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."advancetonextpuzzle"() TO "service_role";
GRANT ALL ON FUNCTION "public"."checkguess"() TO "postgres";
GRANT ALL ON FUNCTION "public"."checkguess"() TO "anon";
GRANT ALL ON FUNCTION "public"."checkguess"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."checkguess"() TO "service_role";
GRANT ALL ON FUNCTION "public"."finishadventure"() TO "postgres";
GRANT ALL ON FUNCTION "public"."finishadventure"() TO "anon";
GRANT ALL ON FUNCTION "public"."finishadventure"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."finishadventure"() TO "service_role";
GRANT ALL ON FUNCTION "public"."gethints"("puzzleid" bigint, "gamecode" character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."gethints"("puzzleid" bigint, "gamecode" character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."gethints"("puzzleid" bigint, "gamecode" character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."getstats"("gamecode" character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."getstats"("gamecode" character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."getstats"("gamecode" character varying) TO "service_role";
GRANT ALL ON FUNCTION "public"."getteamcodejwt"("teamcode" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."getteamcodejwt"("teamcode" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."getteamcodejwt"("teamcode" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."requesthint"("puzzleid" bigint, "gamecode" character varying, "hintid" bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."requesthint"("puzzleid" bigint, "gamecode" character varying, "hintid" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."requesthint"("puzzleid" bigint, "gamecode" character varying, "hintid" bigint) TO "service_role";
GRANT ALL ON FUNCTION "public"."startadventure"() TO "postgres";
GRANT ALL ON FUNCTION "public"."startadventure"() TO "anon";
GRANT ALL ON FUNCTION "public"."startadventure"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."startadventure"() TO "service_role";
GRANT ALL ON FUNCTION "internal"."setteamcode"() TO "postgres";
GRANT ALL ON FUNCTION "internal"."setteamcode"() TO "anon";
GRANT ALL ON FUNCTION "internal"."setteamcode"() TO "authenticated";
GRANT ALL ON FUNCTION "internal"."setteamcode"() TO "service_role";
GRANT ALL ON TABLE "internal"."adjectives" TO "postgres";
GRANT ALL ON TABLE "internal"."adjectives" TO "service_role";
GRANT ALL ON TABLE "internal"."animals" TO "postgres";
GRANT ALL ON TABLE "internal"."animals" TO "service_role";
GRANT ALL ON TABLE "internal"."answers" TO "postgres";
GRANT ALL ON TABLE "internal"."answers" TO "service_role";
GRANT ALL ON TABLE "internal"."colours" TO "postgres";
GRANT ALL ON TABLE "internal"."colours" TO "service_role";
GRANT ALL ON TABLE "internal"."hints" TO "postgres";
GRANT ALL ON TABLE "internal"."hints" TO "service_role";
GRANT ALL ON SEQUENCE "internal"."hints_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "internal"."hints_id_seq" TO "service_role";
GRANT ALL ON TABLE "internal"."secrets" TO "postgres";
GRANT ALL ON TABLE "internal"."secrets" TO "service_role";
GRANT ALL ON TABLE "internal"."usedhints" TO "postgres";
GRANT ALL ON TABLE "internal"."usedhints" TO "service_role";
GRANT ALL ON SEQUENCE "internal"."usedhints_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "internal"."usedhints_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."adventures" TO "postgres";
GRANT ALL ON TABLE "public"."adventures" TO "anon";
GRANT ALL ON TABLE "public"."adventures" TO "authenticated";
GRANT ALL ON TABLE "public"."adventures" TO "service_role";
GRANT ALL ON SEQUENCE "public"."adventures_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."adventures_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."adventures_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."adventures_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."games" TO "postgres";
GRANT ALL ON TABLE "public"."games" TO "anon";
GRANT ALL ON TABLE "public"."games" TO "authenticated";
GRANT ALL ON TABLE "public"."games" TO "service_role";
GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."guesses" TO "postgres";
GRANT ALL ON TABLE "public"."guesses" TO "anon";
GRANT ALL ON TABLE "public"."guesses" TO "authenticated";
GRANT ALL ON TABLE "public"."guesses" TO "service_role";
GRANT ALL ON SEQUENCE "public"."guesses_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."guesses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."guesses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."guesses_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."puzzles" TO "postgres";
GRANT ALL ON TABLE "public"."puzzles" TO "anon";
GRANT ALL ON TABLE "public"."puzzles" TO "authenticated";
GRANT ALL ON TABLE "public"."puzzles" TO "service_role";
GRANT ALL ON SEQUENCE "public"."puzzles_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."puzzles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."puzzles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."puzzles_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TYPES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TYPES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TYPES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TYPES  TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON SEQUENCES  TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON SEQUENCES  TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON TYPES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON TYPES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON TYPES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON TYPES  TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON FUNCTIONS  TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "internal" GRANT ALL ON TABLES  TO "service_role";
