CREATE SCHEMA "internal";
ALTER SCHEMA "internal" OWNER TO "postgres";
ALTER SCHEMA "public" OWNER TO "postgres";
CREATE TABLE "internal"."adjectives" (
    "value" "text" NOT NULL
);
ALTER TABLE "internal"."adjectives" OWNER TO "postgres";
CREATE TABLE "internal"."animals" (
    "value" "text" NOT NULL
);
ALTER TABLE "internal"."animals" OWNER TO "postgres";
CREATE TABLE "internal"."answers" (
    "puzzle" bigint,
    "answer" character varying
);
ALTER TABLE "internal"."answers" OWNER TO "postgres";
CREATE TABLE "internal"."colours" (
    "value" "text" NOT NULL
);
ALTER TABLE "internal"."colours" OWNER TO "postgres";
CREATE TABLE "internal"."hints" (
    "id" bigint NOT NULL,
    "puzzle" bigint,
    "title" character varying,
    "message" character varying,
    "order" bigint
);
ALTER TABLE "internal"."hints" OWNER TO "postgres";
ALTER TABLE "internal"."hints" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "internal"."hints_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE "internal"."secrets" (
    "name" "text" NOT NULL,
    "value" "text" NOT NULL
);
ALTER TABLE "internal"."secrets" OWNER TO "postgres";
CREATE TABLE "internal"."usedhints" (
    "id" bigint NOT NULL,
    "used_at" timestamp with time zone DEFAULT "now"(),
    "hint" bigint,
    "game" character varying
);
ALTER TABLE "internal"."usedhints" OWNER TO "postgres";
ALTER TABLE "internal"."usedhints" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "internal"."usedhints_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE "public"."adventures" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" character varying DEFAULT ''::character varying NOT NULL,
    "description" "text" DEFAULT ''::"text" NOT NULL,
    "price" real DEFAULT '0'::real NOT NULL,
    "public" boolean DEFAULT false NOT NULL,
    "promoBackground" "text",
    "promoLogo" "text",
    "firstPuzzle" bigint
);
ALTER TABLE "public"."adventures" OWNER TO "postgres";
ALTER TABLE "public"."adventures" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."adventures_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE "public"."games" (
    "id" bigint NOT NULL,
    "status" character varying DEFAULT '"UNPAID"'::character varying NOT NULL,
    "code" character varying DEFAULT ''::character varying NOT NULL,
    "user" "uuid",
    "adventure" bigint NOT NULL,
    "puzzle" bigint,
    "startTime" timestamp with time zone,
    "endTime" timestamp with time zone
);
ALTER TABLE "public"."games" OWNER TO "postgres";
ALTER TABLE "public"."games" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."games_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE "public"."guesses" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "content" "text" NOT NULL,
    "puzzle" bigint NOT NULL,
    "game" character varying NOT NULL,
    "correct" boolean DEFAULT false
);
ALTER TABLE "public"."guesses" OWNER TO "postgres";
ALTER TABLE "public"."guesses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."guesses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE "public"."puzzles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "title" "text" DEFAULT ''::"text" NOT NULL,
    "next" bigint,
    "content" "text" NOT NULL,
    "adventure" bigint NOT NULL,
    "storage_slug" character varying NOT NULL
);
ALTER TABLE "public"."puzzles" OWNER TO "postgres";
ALTER TABLE "public"."puzzles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."puzzles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "internal"."adjectives"
    ADD CONSTRAINT "adjectives_pkey" PRIMARY KEY ("value");
ALTER TABLE ONLY "internal"."adjectives"
    ADD CONSTRAINT "adjectives_value_key" UNIQUE ("value");
ALTER TABLE ONLY "internal"."animals"
    ADD CONSTRAINT "animals_pkey" PRIMARY KEY ("value");
ALTER TABLE ONLY "internal"."colours"
    ADD CONSTRAINT "colours_pkey" PRIMARY KEY ("value");
ALTER TABLE ONLY "internal"."hints"
    ADD CONSTRAINT "hints_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "internal"."usedhints"
    ADD CONSTRAINT "one_unlock_per_hint" UNIQUE ("hint", "game");
ALTER TABLE ONLY "internal"."secrets"
    ADD CONSTRAINT "secrets_name_key" UNIQUE ("name");
ALTER TABLE ONLY "internal"."hints"
    ADD CONSTRAINT "unique_puzzle_ordering" UNIQUE ("puzzle", "order");
ALTER TABLE ONLY "internal"."usedhints"
    ADD CONSTRAINT "usedhints_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."adventures"
    ADD CONSTRAINT "adventures_name_key" UNIQUE ("name");
ALTER TABLE ONLY "public"."adventures"
    ADD CONSTRAINT "adventures_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_code_key" UNIQUE ("code");
ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_id_key" UNIQUE ("id");
ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."guesses"
    ADD CONSTRAINT "guesses_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."puzzles"
    ADD CONSTRAINT "puzzles_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."adventures"
    ADD CONSTRAINT "unique_name" UNIQUE ("name");
ALTER TABLE ONLY "public"."puzzles"
    ADD CONSTRAINT "unique_slug" UNIQUE ("storage_slug");
ALTER TABLE ONLY "internal"."answers"
    ADD CONSTRAINT "answers_puzzle_fkey" FOREIGN KEY ("puzzle") REFERENCES "public"."puzzles"("id");
ALTER TABLE "internal"."answers"
    ADD CONSTRAINT "unique_answer" UNIQUE ("puzzle", "answer");
ALTER TABLE ONLY "internal"."hints"
    ADD CONSTRAINT "hints_puzzle_fkey" FOREIGN KEY ("puzzle") REFERENCES "public"."puzzles"("id");
ALTER TABLE ONLY "internal"."usedhints"
    ADD CONSTRAINT "usedhints_game_fkey" FOREIGN KEY ("game") REFERENCES "public"."games"("code");
ALTER TABLE ONLY "internal"."usedhints"
    ADD CONSTRAINT "usedhints_hint_fkey" FOREIGN KEY ("hint") REFERENCES "internal"."hints"("id");
ALTER TABLE ONLY "public"."adventures"
    ADD CONSTRAINT "adventures_firstPuzzle_fkey" FOREIGN KEY ("firstPuzzle") REFERENCES "public"."puzzles"("id");
ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_adventure_fkey" FOREIGN KEY ("adventure") REFERENCES "public"."adventures"("id");
ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_puzzle_fkey" FOREIGN KEY ("puzzle") REFERENCES "public"."puzzles"("id");
ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_user_fkey" FOREIGN KEY ("user") REFERENCES "auth"."users"("id") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."guesses"
    ADD CONSTRAINT "guesses_game_fkey" FOREIGN KEY ("game") REFERENCES "public"."games"("code");
ALTER TABLE ONLY "public"."guesses"
    ADD CONSTRAINT "guesses_puzzle_fkey" FOREIGN KEY ("puzzle") REFERENCES "public"."puzzles"("id");
ALTER TABLE ONLY "public"."puzzles"
    ADD CONSTRAINT "puzzles_adventure_fkey" FOREIGN KEY ("adventure") REFERENCES "public"."adventures"("id");
ALTER TABLE ONLY "public"."puzzles"
    ADD CONSTRAINT "puzzles_next_fkey" FOREIGN KEY ("next") REFERENCES "public"."puzzles"("id");
